// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: connector/v1/connector.proto

package connectorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceMeta 是连接器声明的服务元数据（握手时上报，网关校验后转发控制台自动登记）。
type ServiceMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 服务名：与凭证绑定（凭证签发时声明，连接器不得改名）。
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 本次接入声明的域名（必须是凭证 hosts 白名单的子集；网关按它建立 Host→会话路由）。
	Hosts []string `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	// 连接器侧真实业务地址（如 http://127.0.0.1:8080）——纯观测字段，控制台展示用。
	LocalAddr string `protobuf:"bytes,3,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	// 连接器（SDK / shen-connector 二进制）版本——运维提示用。
	ConnectorVersion string `protobuf:"bytes,4,opt,name=connector_version,json=connectorVersion,proto3" json:"connector_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceMeta) Reset() {
	*x = ServiceMeta{}
	mi := &file_connector_v1_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMeta) ProtoMessage() {}

func (x *ServiceMeta) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v1_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMeta.ProtoReflect.Descriptor instead.
func (*ServiceMeta) Descriptor() ([]byte, []int) {
	return file_connector_v1_connector_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceMeta) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *ServiceMeta) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *ServiceMeta) GetConnectorVersion() string {
	if x != nil {
		return x.ConnectorVersion
	}
	return ""
}

// HandshakeRequest 是流 0 的第一条消息：认证 + 声明。
type HandshakeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// shc- 开头的接入凭证；仅此一次跨线明文（TLS 内）。
	AuthKey string       `protobuf:"bytes,1,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	Meta    *ServiceMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	// ── v2 预留：mTLS 第二因子（v1 不填）────────────────────────────────
	// 客户端证书 PEM（网关持有 CA 时校验；与 auth_key 构成双因子）。
	ClientCertPem string `protobuf:"bytes,16,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_connector_v1_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v1_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_connector_v1_connector_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *HandshakeRequest) GetMeta() *ServiceMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *HandshakeRequest) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

// HandshakeResponse 是握手的应答。
type HandshakeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// 网关分配的会话 ID（观测面与日志对账用）。
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 失败原因（面向运维的人话，**不含密钥**）。
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// 心跳间隔（秒；yamux keepalive ping 周期，0 = 网关默认）。
	KeepaliveSeconds uint32 `protobuf:"varint,4,opt,name=keepalive_seconds,json=keepaliveSeconds,proto3" json:"keepalive_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_connector_v1_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v1_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_connector_v1_connector_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HandshakeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HandshakeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HandshakeResponse) GetKeepaliveSeconds() uint32 {
	if x != nil {
		return x.KeepaliveSeconds
	}
	return 0
}

// SessionEvent 是控制信道上的异步事件（握手成功后，双向皆可发）。
//
// v1 只定义一种用途：连接器主动告知「即将下线」（kind="closing"），
// 让网关与会话观测面把「计划内下线」与「意外掉线」区分开——审计质量的关键。
type SessionEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// closing：连接器主动下线。其余取值 v2 扩展。
	Kind          string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Detail        string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_connector_v1_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v1_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_connector_v1_connector_proto_rawDescGZIP(), []int{3}
}

func (x *SessionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SessionEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_connector_v1_connector_proto protoreflect.FileDescriptor

const file_connector_v1_connector_proto_rawDesc = "" +
	"\n" +
	"\x1cconnector/v1/connector.proto\x12\fconnector.v1\"\x83\x01\n" +
	"\vServiceMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05hosts\x18\x02 \x03(\tR\x05hosts\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x03 \x01(\tR\tlocalAddr\x12+\n" +
	"\x11connector_version\x18\x04 \x01(\tR\x10connectorVersion\"\x84\x01\n" +
	"\x10HandshakeRequest\x12\x19\n" +
	"\bauth_key\x18\x01 \x01(\tR\aauthKey\x12-\n" +
	"\x04meta\x18\x02 \x01(\v2\x19.connector.v1.ServiceMetaR\x04meta\x12&\n" +
	"\x0fclient_cert_pem\x18\x10 \x01(\tR\rclientCertPem\"\x85\x01\n" +
	"\x11HandshakeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12+\n" +
	"\x11keepalive_seconds\x18\x04 \x01(\rR\x10keepaliveSeconds\"Y\n" +
	"\fSessionEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detailB*Z(shen/common/api/connector/v1;connectorv1b\x06proto3"

var (
	file_connector_v1_connector_proto_rawDescOnce sync.Once
	file_connector_v1_connector_proto_rawDescData []byte
)

func file_connector_v1_connector_proto_rawDescGZIP() []byte {
	file_connector_v1_connector_proto_rawDescOnce.Do(func() {
		file_connector_v1_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connector_v1_connector_proto_rawDesc), len(file_connector_v1_connector_proto_rawDesc)))
	})
	return file_connector_v1_connector_proto_rawDescData
}

var file_connector_v1_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_connector_v1_connector_proto_goTypes = []any{
	(*ServiceMeta)(nil),       // 0: connector.v1.ServiceMeta
	(*HandshakeRequest)(nil),  // 1: connector.v1.HandshakeRequest
	(*HandshakeResponse)(nil), // 2: connector.v1.HandshakeResponse
	(*SessionEvent)(nil),      // 3: connector.v1.SessionEvent
}
var file_connector_v1_connector_proto_depIdxs = []int32{
	0, // 0: connector.v1.HandshakeRequest.meta:type_name -> connector.v1.ServiceMeta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_connector_v1_connector_proto_init() }
func file_connector_v1_connector_proto_init() {
	if File_connector_v1_connector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connector_v1_connector_proto_rawDesc), len(file_connector_v1_connector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connector_v1_connector_proto_goTypes,
		DependencyIndexes: file_connector_v1_connector_proto_depIdxs,
		MessageInfos:      file_connector_v1_connector_proto_msgTypes,
	}.Build()
	File_connector_v1_connector_proto = out.File
	file_connector_v1_connector_proto_goTypes = nil
	file_connector_v1_connector_proto_depIdxs = nil
}
