// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: judge/v1/judge.proto

package judgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeceptionJudge_Judge_FullMethodName = "/judge.v1.DeceptionJudge/Judge"
)

// DeceptionJudgeClient is the client API for DeceptionJudge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 判定面 —— 适配器经此调用核心（接缝 S1）
// 候选对比与失效条件见 docs/background/decisions/0002-decision-model.md
type DeceptionJudgeClient interface {
	Judge(ctx context.Context, in *JudgeRequest, opts ...grpc.CallOption) (*JudgeResponse, error)
}

type deceptionJudgeClient struct {
	cc grpc.ClientConnInterface
}

func NewDeceptionJudgeClient(cc grpc.ClientConnInterface) DeceptionJudgeClient {
	return &deceptionJudgeClient{cc}
}

func (c *deceptionJudgeClient) Judge(ctx context.Context, in *JudgeRequest, opts ...grpc.CallOption) (*JudgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JudgeResponse)
	err := c.cc.Invoke(ctx, DeceptionJudge_Judge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeceptionJudgeServer is the server API for DeceptionJudge service.
// All implementations must embed UnimplementedDeceptionJudgeServer
// for forward compatibility.
//
// 判定面 —— 适配器经此调用核心（接缝 S1）
// 候选对比与失效条件见 docs/background/decisions/0002-decision-model.md
type DeceptionJudgeServer interface {
	Judge(context.Context, *JudgeRequest) (*JudgeResponse, error)
	mustEmbedUnimplementedDeceptionJudgeServer()
}

// UnimplementedDeceptionJudgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeceptionJudgeServer struct{}

func (UnimplementedDeceptionJudgeServer) Judge(context.Context, *JudgeRequest) (*JudgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Judge not implemented")
}
func (UnimplementedDeceptionJudgeServer) mustEmbedUnimplementedDeceptionJudgeServer() {}
func (UnimplementedDeceptionJudgeServer) testEmbeddedByValue()                        {}

// UnsafeDeceptionJudgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeceptionJudgeServer will
// result in compilation errors.
type UnsafeDeceptionJudgeServer interface {
	mustEmbedUnimplementedDeceptionJudgeServer()
}

func RegisterDeceptionJudgeServer(s grpc.ServiceRegistrar, srv DeceptionJudgeServer) {
	// If the following call panics, it indicates UnimplementedDeceptionJudgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeceptionJudge_ServiceDesc, srv)
}

func _DeceptionJudge_Judge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JudgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeceptionJudgeServer).Judge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeceptionJudge_Judge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeceptionJudgeServer).Judge(ctx, req.(*JudgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeceptionJudge_ServiceDesc is the grpc.ServiceDesc for DeceptionJudge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeceptionJudge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "judge.v1.DeceptionJudge",
	HandlerType: (*DeceptionJudgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Judge",
			Handler:    _DeceptionJudge_Judge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "judge/v1/judge.proto",
}
