// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: judge/v1/judge.proto

package judgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 三值闭集，禁止新增第四个取值（MD-12 / TM-12）
// ACTION_UNSPECIFIED 一律按 ACTION_ORIGIN 处理（NI-5 / V-4）
type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_ORIGIN      Action = 1 // route_origin
	Action_ACTION_MIRAGE      Action = 2 // route_mirage
	Action_ACTION_BLOCK       Action = 3 // block
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_ORIGIN",
		2: "ACTION_MIRAGE",
		3: "ACTION_BLOCK",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_ORIGIN":      1,
		"ACTION_MIRAGE":      2,
		"ACTION_BLOCK":       3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_judge_v1_judge_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_judge_v1_judge_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_judge_v1_judge_proto_rawDescGZIP(), []int{0}
}

// 当前唯一合法值（TM-13 / MD-24）
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_NONE        Severity = 1
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_NONE",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_NONE":        1,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_judge_v1_judge_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_judge_v1_judge_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_judge_v1_judge_proto_rawDescGZIP(), []int{1}
}

type JudgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 幂等键，由适配器按（来源标识, 会话, 路径, 时间窗）派生（ST-10）
	DecisionId    string       `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Observed      *Observation `protobuf:"bytes,2,opt,name=observed,proto3" json:"observed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeRequest) Reset() {
	*x = JudgeRequest{}
	mi := &file_judge_v1_judge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeRequest) ProtoMessage() {}

func (x *JudgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_judge_v1_judge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeRequest.ProtoReflect.Descriptor instead.
func (*JudgeRequest) Descriptor() ([]byte, []int) {
	return file_judge_v1_judge_proto_rawDescGZIP(), []int{0}
}

func (x *JudgeRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *JudgeRequest) GetObserved() *Observation {
	if x != nil {
		return x.Observed
	}
	return nil
}

// 首跳可用信息（D0 推论 1）
type Observation struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SourceIp  string                 `protobuf:"bytes,1,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	UserAgent string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Method    string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// path **不含**查询串（与 HTTP 语义一致）。
	Path           string            `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	TlsFingerprint string            `protobuf:"bytes,5,opt,name=tls_fingerprint,json=tlsFingerprint,proto3" json:"tls_fingerprint,omitempty"`
	Headers        map[string]string `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// query 是查询串的**规范化匹配视图**（不含前导 `?`），供规则匹配。
	//
	// 三方约定（proto / 适配器 / 规则引擎必须一致）：**反复解码到不动点，上限 3 轮**
	// （`%252e` → `%2e` → `.`；`+` 与 `%20` → 空格）；出错或不再变化即停。
	// 为什么要解到不动点：只解一轮时「二次编码」（`%252e%252e`）仍可绕过 —— 那是实测缺口。
	// 为什么有上限：每轮解码都是对**攻击者可控输入**的线性工作；上限把成本钉死，
	// 代价是三重及以上编码仍可能绕过（已登记，见 docs/spec/config.md §2.4）。
	// ⚠️ 它只用于**匹配**：转发给上游的仍是原始请求行，原样字节见 `query_raw`。
	Query string `protobuf:"bytes,7,opt,name=query,proto3" json:"query,omitempty"`
	// query_raw 是客户端**原样发来**的查询串（未解码），供审计与「按编码形态匹配」的规则使用。
	//
	// 为什么要它：`AR-31` 要求攻击者可控字段原样保留；而且「编码本身就是信号」——
	// 想匹配 `%2e%2e` / `%00` 这类形态，只能在原样字段上做（规范化后的字段已经没有编码了）。
	QueryRaw      string `protobuf:"bytes,8,opt,name=query_raw,json=queryRaw,proto3" json:"query_raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_judge_v1_judge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_judge_v1_judge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_judge_v1_judge_proto_rawDescGZIP(), []int{1}
}

func (x *Observation) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *Observation) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Observation) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Observation) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Observation) GetTlsFingerprint() string {
	if x != nil {
		return x.TlsFingerprint
	}
	return ""
}

func (x *Observation) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Observation) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Observation) GetQueryRaw() string {
	if x != nil {
		return x.QueryRaw
	}
	return ""
}

type JudgeResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Action Action                 `protobuf:"varint,1,opt,name=action,proto3,enum=judge.v1.Action" json:"action,omitempty"`
	// 旁路字段，与 action 并列输出（MD-13）
	Severity Severity `protobuf:"varint,2,opt,name=severity,proto3,enum=judge.v1.Severity" json:"severity,omitempty"`
	// 仅 ACTION_MIRAGE 时非空
	Backend       string `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"` // 注意 ST-7：禁止在此回显风险分值、规则名或证据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeResponse) Reset() {
	*x = JudgeResponse{}
	mi := &file_judge_v1_judge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeResponse) ProtoMessage() {}

func (x *JudgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_judge_v1_judge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeResponse.ProtoReflect.Descriptor instead.
func (*JudgeResponse) Descriptor() ([]byte, []int) {
	return file_judge_v1_judge_proto_rawDescGZIP(), []int{2}
}

func (x *JudgeResponse) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *JudgeResponse) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *JudgeResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

var File_judge_v1_judge_proto protoreflect.FileDescriptor

const file_judge_v1_judge_proto_rawDesc = "" +
	"\n" +
	"\x14judge/v1/judge.proto\x12\bjudge.v1\"b\n" +
	"\fJudgeRequest\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x121\n" +
	"\bobserved\x18\x02 \x01(\v2\x15.judge.v1.ObservationR\bobserved\"\xcb\x02\n" +
	"\vObservation\x12\x1b\n" +
	"\tsource_ip\x18\x01 \x01(\tR\bsourceIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12'\n" +
	"\x0ftls_fingerprint\x18\x05 \x01(\tR\x0etlsFingerprint\x12<\n" +
	"\aheaders\x18\x06 \x03(\v2\".judge.v1.Observation.HeadersEntryR\aheaders\x12\x14\n" +
	"\x05query\x18\a \x01(\tR\x05query\x12\x1b\n" +
	"\tquery_raw\x18\b \x01(\tR\bqueryRaw\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\rJudgeResponse\x12(\n" +
	"\x06action\x18\x01 \x01(\x0e2\x10.judge.v1.ActionR\x06action\x12.\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x12.judge.v1.SeverityR\bseverity\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend*X\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACTION_ORIGIN\x10\x01\x12\x11\n" +
	"\rACTION_MIRAGE\x10\x02\x12\x10\n" +
	"\fACTION_BLOCK\x10\x03*7\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_NONE\x10\x012J\n" +
	"\x0eDeceptionJudge\x128\n" +
	"\x05Judge\x12\x16.judge.v1.JudgeRequest\x1a\x17.judge.v1.JudgeResponseB\"Z shen/common/api/judge/v1;judgev1b\x06proto3"

var (
	file_judge_v1_judge_proto_rawDescOnce sync.Once
	file_judge_v1_judge_proto_rawDescData []byte
)

func file_judge_v1_judge_proto_rawDescGZIP() []byte {
	file_judge_v1_judge_proto_rawDescOnce.Do(func() {
		file_judge_v1_judge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_judge_v1_judge_proto_rawDesc), len(file_judge_v1_judge_proto_rawDesc)))
	})
	return file_judge_v1_judge_proto_rawDescData
}

var file_judge_v1_judge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_judge_v1_judge_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_judge_v1_judge_proto_goTypes = []any{
	(Action)(0),           // 0: judge.v1.Action
	(Severity)(0),         // 1: judge.v1.Severity
	(*JudgeRequest)(nil),  // 2: judge.v1.JudgeRequest
	(*Observation)(nil),   // 3: judge.v1.Observation
	(*JudgeResponse)(nil), // 4: judge.v1.JudgeResponse
	nil,                   // 5: judge.v1.Observation.HeadersEntry
}
var file_judge_v1_judge_proto_depIdxs = []int32{
	3, // 0: judge.v1.JudgeRequest.observed:type_name -> judge.v1.Observation
	5, // 1: judge.v1.Observation.headers:type_name -> judge.v1.Observation.HeadersEntry
	0, // 2: judge.v1.JudgeResponse.action:type_name -> judge.v1.Action
	1, // 3: judge.v1.JudgeResponse.severity:type_name -> judge.v1.Severity
	2, // 4: judge.v1.DeceptionJudge.Judge:input_type -> judge.v1.JudgeRequest
	4, // 5: judge.v1.DeceptionJudge.Judge:output_type -> judge.v1.JudgeResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_judge_v1_judge_proto_init() }
func file_judge_v1_judge_proto_init() {
	if File_judge_v1_judge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_judge_v1_judge_proto_rawDesc), len(file_judge_v1_judge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_judge_v1_judge_proto_goTypes,
		DependencyIndexes: file_judge_v1_judge_proto_depIdxs,
		EnumInfos:         file_judge_v1_judge_proto_enumTypes,
		MessageInfos:      file_judge_v1_judge_proto_msgTypes,
	}.Build()
	File_judge_v1_judge_proto = out.File
	file_judge_v1_judge_proto_goTypes = nil
	file_judge_v1_judge_proto_depIdxs = nil
}
