# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from analysis.proto.telemetry.v1 import telemetry_pb2 as telemetry_dot_v1_dot_telemetry__pb2

GRPC_GENERATED_VERSION = "1.84.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in telemetry/v1/telemetry_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DeceptionTelemetryStub:
    """遥测面 —— 异步、批量、幂等（AR-11）"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Report = channel.unary_unary(
            "/telemetry.v1.DeceptionTelemetry/Report",
            request_serializer=telemetry_dot_v1_dot_telemetry__pb2.TelemetryEvent.SerializeToString,
            response_deserializer=telemetry_dot_v1_dot_telemetry__pb2.ReportAck.FromString,
            _registered_method=True,
        )
        self.ReportBatch = channel.unary_unary(
            "/telemetry.v1.DeceptionTelemetry/ReportBatch",
            request_serializer=telemetry_dot_v1_dot_telemetry__pb2.TelemetryBatch.SerializeToString,
            response_deserializer=telemetry_dot_v1_dot_telemetry__pb2.ReportAck.FromString,
            _registered_method=True,
        )
        self.ListEvents = channel.unary_unary(
            "/telemetry.v1.DeceptionTelemetry/ListEvents",
            request_serializer=telemetry_dot_v1_dot_telemetry__pb2.ListEventsRequest.SerializeToString,
            response_deserializer=telemetry_dot_v1_dot_telemetry__pb2.ListEventsResponse.FromString,
            _registered_method=True,
        )


class DeceptionTelemetryServicer:
    """遥测面 —— 异步、批量、幂等（AR-11）"""

    def Report(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReportBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListEvents(self, request, context):
        """读侧：列出最近事件（观测面）。

        用途：控制台回答「刚才发生了什么、告警在哪、流量怎么流动」——
        这是**人工测试与排障**的基础能力，也是 `logs.md` 字典落地前的过渡读侧契约。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DeceptionTelemetryServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Report": grpc.unary_unary_rpc_method_handler(
            servicer.Report,
            request_deserializer=telemetry_dot_v1_dot_telemetry__pb2.TelemetryEvent.FromString,
            response_serializer=telemetry_dot_v1_dot_telemetry__pb2.ReportAck.SerializeToString,
        ),
        "ReportBatch": grpc.unary_unary_rpc_method_handler(
            servicer.ReportBatch,
            request_deserializer=telemetry_dot_v1_dot_telemetry__pb2.TelemetryBatch.FromString,
            response_serializer=telemetry_dot_v1_dot_telemetry__pb2.ReportAck.SerializeToString,
        ),
        "ListEvents": grpc.unary_unary_rpc_method_handler(
            servicer.ListEvents,
            request_deserializer=telemetry_dot_v1_dot_telemetry__pb2.ListEventsRequest.FromString,
            response_serializer=telemetry_dot_v1_dot_telemetry__pb2.ListEventsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "telemetry.v1.DeceptionTelemetry", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("telemetry.v1.DeceptionTelemetry", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class DeceptionTelemetry:
    """遥测面 —— 异步、批量、幂等（AR-11）"""

    @staticmethod
    def Report(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/telemetry.v1.DeceptionTelemetry/Report",
            telemetry_dot_v1_dot_telemetry__pb2.TelemetryEvent.SerializeToString,
            telemetry_dot_v1_dot_telemetry__pb2.ReportAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReportBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/telemetry.v1.DeceptionTelemetry/ReportBatch",
            telemetry_dot_v1_dot_telemetry__pb2.TelemetryBatch.SerializeToString,
            telemetry_dot_v1_dot_telemetry__pb2.ReportAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListEvents(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/telemetry.v1.DeceptionTelemetry/ListEvents",
            telemetry_dot_v1_dot_telemetry__pb2.ListEventsRequest.SerializeToString,
            telemetry_dot_v1_dot_telemetry__pb2.ListEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
