# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from analysis.proto.telemetry.v1 import telemetry_pb2 as telemetry_dot_v1_dot_telemetry__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in telemetry/v1/telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeceptionTelemetryStub:
    """遥测面 —— 异步、批量、幂等（AR-11）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Report = channel.unary_unary(
                '/telemetry.v1.DeceptionTelemetry/Report',
                request_serializer=telemetry_dot_v1_dot_telemetry__pb2.TelemetryEvent.SerializeToString,
                response_deserializer=telemetry_dot_v1_dot_telemetry__pb2.ReportAck.FromString,
                _registered_method=True)
        self.ReportBatch = channel.unary_unary(
                '/telemetry.v1.DeceptionTelemetry/ReportBatch',
                request_serializer=telemetry_dot_v1_dot_telemetry__pb2.TelemetryBatch.SerializeToString,
                response_deserializer=telemetry_dot_v1_dot_telemetry__pb2.ReportAck.FromString,
                _registered_method=True)
        self.ListEvents = channel.unary_unary(
                '/telemetry.v1.DeceptionTelemetry/ListEvents',
                request_serializer=telemetry_dot_v1_dot_telemetry__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=telemetry_dot_v1_dot_telemetry__pb2.ListEventsResponse.FromString,
                _registered_method=True)
        self.GetCoreSnapshot = channel.unary_unary(
                '/telemetry.v1.DeceptionTelemetry/GetCoreSnapshot',
                request_serializer=telemetry_dot_v1_dot_telemetry__pb2.GetCoreSnapshotRequest.SerializeToString,
                response_deserializer=telemetry_dot_v1_dot_telemetry__pb2.CoreSnapshot.FromString,
                _registered_method=True)
        self.WatchEvents = channel.unary_stream(
                '/telemetry.v1.DeceptionTelemetry/WatchEvents',
                request_serializer=telemetry_dot_v1_dot_telemetry__pb2.WatchEventsRequest.SerializeToString,
                response_deserializer=telemetry_dot_v1_dot_telemetry__pb2.WatchEvent.FromString,
                _registered_method=True)


class DeceptionTelemetryServicer:
    """遥测面 —— 异步、批量、幂等（AR-11）
    """

    def Report(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvents(self, request, context):
        """读侧：列出最近事件（观测面）。

        用途：控制台回答「刚才发生了什么、告警在哪、流量怎么流动」——
        这是**人工测试与排障**的基础能力，也是 `logs.md` 字典落地前的过渡读侧契约。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoreSnapshot(self, request, context):
        """读侧：**核心当前生效状态的只读快照**（配置 + 策略版本 + AI 能力装载态）。

        用途：控制台回答「这套引擎现在是按什么在跑」—— 配置与内容清单活在**核心内存**里，
        控制台拿不到，只能问核心要（见 `docs/spec/console-api.md` §2）。

        语义：**纯读**。与 `policy.Pull` 不同：它**不**推进任何游标、**不**写任何状态 ——
        控制台随时刷新都不会影响适配器的策略对账（`ST-8`）。

        刻意**不**返回：白名单/隔离名单的**内容**（只给条数）、任何密钥（`ST-20`）。
        观测面不等于泄密面：控制台是只读观测台，不是配置导出器。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchEvents(self, request, context):
        """读侧：**订阅新事件**（观测面推送，`ADR-0027`）。

        与 `ListEvents` 的分工：`ListEvents` 回答「刚才发生了什么」（**拉**，有窗口）；
        `WatchEvents` 回答「**正在发生什么**」（**推**，长连接）。

        三条不可破的语义：

        ① **旁路**：推送在落库之后进行，投递失败**不得**影响任何写入路径（`NI-1` / `AR-6`）；
        ② **无背压**：订阅者跟不上就**丢**（每订阅者有界缓冲 + 丢最旧），丢了多少**随流告知**；
        ③ **可补漏**：`since` 非空时先补一段历史再转流 —— 断线重连不静默丢数据。

        刻意**不**在服务端保留事件（那是 `store` 的事）：流的缓冲只是投递队列，不是历史。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeceptionTelemetryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Report': grpc.unary_unary_rpc_method_handler(
                    servicer.Report,
                    request_deserializer=telemetry_dot_v1_dot_telemetry__pb2.TelemetryEvent.FromString,
                    response_serializer=telemetry_dot_v1_dot_telemetry__pb2.ReportAck.SerializeToString,
            ),
            'ReportBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportBatch,
                    request_deserializer=telemetry_dot_v1_dot_telemetry__pb2.TelemetryBatch.FromString,
                    response_serializer=telemetry_dot_v1_dot_telemetry__pb2.ReportAck.SerializeToString,
            ),
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=telemetry_dot_v1_dot_telemetry__pb2.ListEventsRequest.FromString,
                    response_serializer=telemetry_dot_v1_dot_telemetry__pb2.ListEventsResponse.SerializeToString,
            ),
            'GetCoreSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoreSnapshot,
                    request_deserializer=telemetry_dot_v1_dot_telemetry__pb2.GetCoreSnapshotRequest.FromString,
                    response_serializer=telemetry_dot_v1_dot_telemetry__pb2.CoreSnapshot.SerializeToString,
            ),
            'WatchEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchEvents,
                    request_deserializer=telemetry_dot_v1_dot_telemetry__pb2.WatchEventsRequest.FromString,
                    response_serializer=telemetry_dot_v1_dot_telemetry__pb2.WatchEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.v1.DeceptionTelemetry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telemetry.v1.DeceptionTelemetry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeceptionTelemetry:
    """遥测面 —— 异步、批量、幂等（AR-11）
    """

    @staticmethod
    def Report(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telemetry.v1.DeceptionTelemetry/Report',
            telemetry_dot_v1_dot_telemetry__pb2.TelemetryEvent.SerializeToString,
            telemetry_dot_v1_dot_telemetry__pb2.ReportAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telemetry.v1.DeceptionTelemetry/ReportBatch',
            telemetry_dot_v1_dot_telemetry__pb2.TelemetryBatch.SerializeToString,
            telemetry_dot_v1_dot_telemetry__pb2.ReportAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telemetry.v1.DeceptionTelemetry/ListEvents',
            telemetry_dot_v1_dot_telemetry__pb2.ListEventsRequest.SerializeToString,
            telemetry_dot_v1_dot_telemetry__pb2.ListEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoreSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telemetry.v1.DeceptionTelemetry/GetCoreSnapshot',
            telemetry_dot_v1_dot_telemetry__pb2.GetCoreSnapshotRequest.SerializeToString,
            telemetry_dot_v1_dot_telemetry__pb2.CoreSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/telemetry.v1.DeceptionTelemetry/WatchEvents',
            telemetry_dot_v1_dot_telemetry__pb2.WatchEventsRequest.SerializeToString,
            telemetry_dot_v1_dot_telemetry__pb2.WatchEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
