# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry/v1/telemetry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "telemetry/v1/telemetry.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1ctelemetry/v1/telemetry.proto\x12\x0ctelemetry.v1\x1a\x1fgoogle/protobuf/timestamp.proto"\x9d\x01\n\x0eTelemetryEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x10\n\x08\x61\x63tor_id\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp">\n\x0eTelemetryBatch\x12,\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x1c.telemetry.v1.TelemetryEvent"a\n\x11ListEventsRequest\x12\r\n\x05limit\x18\x01 \x01(\r\x12)\n\x05since\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nevent_type\x18\x03 \x01(\t"B\n\x12ListEventsResponse\x12,\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x1c.telemetry.v1.TelemetryEvent"1\n\tReportAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\r\x12\x12\n\nduplicated\x18\x02 \x01(\r2\xec\x01\n\x12\x44\x65\x63\x65ptionTelemetry\x12?\n\x06Report\x12\x1c.telemetry.v1.TelemetryEvent\x1a\x17.telemetry.v1.ReportAck\x12\x44\n\x0bReportBatch\x12\x1c.telemetry.v1.TelemetryBatch\x1a\x17.telemetry.v1.ReportAck\x12O\n\nListEvents\x12\x1f.telemetry.v1.ListEventsRequest\x1a .telemetry.v1.ListEventsResponseB#Z!shen/api/telemetry/v1;telemetryv1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "telemetry.v1.telemetry_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z!shen/api/telemetry/v1;telemetryv1"
    _globals["_TELEMETRYEVENT"]._serialized_start = 80
    _globals["_TELEMETRYEVENT"]._serialized_end = 237
    _globals["_TELEMETRYBATCH"]._serialized_start = 239
    _globals["_TELEMETRYBATCH"]._serialized_end = 301
    _globals["_LISTEVENTSREQUEST"]._serialized_start = 303
    _globals["_LISTEVENTSREQUEST"]._serialized_end = 400
    _globals["_LISTEVENTSRESPONSE"]._serialized_start = 402
    _globals["_LISTEVENTSRESPONSE"]._serialized_end = 468
    _globals["_REPORTACK"]._serialized_start = 470
    _globals["_REPORTACK"]._serialized_end = 519
    _globals["_DECEPTIONTELEMETRY"]._serialized_start = 522
    _globals["_DECEPTIONTELEMETRY"]._serialized_end = 758
# @@protoc_insertion_point(module_scope)
