// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: telemetry/v1/telemetry.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WatchEventsRequest 是订阅参数。
type WatchEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 只订阅这些事件类型；**空 = 全部**。过滤在服务端做（订阅者不必自己丢无用的）。
	EventTypes []string `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	// 补漏起点：非空时先补「该时刻之后、最多 catch_up_limit 条」的历史，再转流。
	Since *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	// 补漏上限；0 = 服务端默认（500）。防止断线很久后一次灌爆客户端。
	CatchUpLimit uint32 `protobuf:"varint,3,opt,name=catch_up_limit,json=catchUpLimit,proto3" json:"catch_up_limit,omitempty"`
	// 订阅者标识（进日志，便于分辨「谁在订阅」）。
	SubscriberId  string `protobuf:"bytes,4,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *WatchEventsRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *WatchEventsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *WatchEventsRequest) GetCatchUpLimit() uint32 {
	if x != nil {
		return x.CatchUpLimit
	}
	return 0
}

func (x *WatchEventsRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

// WatchEvent 是流上的一条消息：**事件**或**流自身状态**。
//
// 为什么不用裸 `TelemetryEvent` 流：订阅者需要知道「我漏了多少」——
// 丢事件是无背压的必然代价（见 `WatchEvents` 语义②）。状态帧让丢包**可见**，
// 而不是让页面把「漏了」误读成「没发生」。
type WatchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*WatchEvent_Event
	//	*WatchEvent_Status
	Body          isWatchEvent_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *WatchEvent) GetBody() isWatchEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WatchEvent) GetEvent() *TelemetryEvent {
	if x != nil {
		if x, ok := x.Body.(*WatchEvent_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *WatchEvent) GetStatus() *WatchStatus {
	if x != nil {
		if x, ok := x.Body.(*WatchEvent_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isWatchEvent_Body interface {
	isWatchEvent_Body()
}

type WatchEvent_Event struct {
	Event *TelemetryEvent `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type WatchEvent_Status struct {
	Status *WatchStatus `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*WatchEvent_Event) isWatchEvent_Body() {}

func (*WatchEvent_Status) isWatchEvent_Body() {}

// WatchStatus 是本订阅者的缓冲区状态（服务端只在**有变化时**发，不刷屏）。
type WatchStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// dropped = 本订阅者累计被丢弃的事件数（缓冲满时丢最旧 / 塞不进）。
	Dropped uint64 `protobuf:"varint,1,opt,name=dropped,proto3" json:"dropped,omitempty"`
	// buffer_size = 当前缓冲里待投递的条数（越大说明订阅者越慢）。
	BufferSize uint32 `protobuf:"varint,2,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	// capacity = 本订阅者的缓冲容量（常量，便于客户端自解释）。
	Capacity      uint32 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchStatus) Reset() {
	*x = WatchStatus{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStatus) ProtoMessage() {}

func (x *WatchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStatus.ProtoReflect.Descriptor instead.
func (*WatchStatus) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *WatchStatus) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *WatchStatus) GetBufferSize() uint32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

func (x *WatchStatus) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

// GetCoreSnapshotRequest 无参数 —— 快照就是「现在」，不接受时间窗（要历史去读事件）。
type GetCoreSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoreSnapshotRequest) Reset() {
	*x = GetCoreSnapshotRequest{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoreSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoreSnapshotRequest) ProtoMessage() {}

func (x *GetCoreSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoreSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetCoreSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

// CoreSnapshot 是核心当前生效状态的只读摘要。
//
// **字段取舍有规矩**（见 `docs/spec/console-api.md` §2.1）：只放两类 ——
//
//  1. 已经**允许离开核心**的（策略版本 / 校验和 / AI 配置，它们本就在 `api/policy/v1` 的载荷里）；
//  2. 比前者**更弱**的描述性信息（如白名单**条数** —— 载荷里本来就有全量 CIDR 列表）。
//
// 因此**不**包含：阈值 / 灰度 / 误调度预算 / 影子模式 ——
// 它们是核心运行参数，`core/internal/contract/thresholds.go` 明确禁止写进 `api/*.proto` 的对外响应
// （`ST-23` 要求它们集中定义并可配置，不代表可以把它们摊到契约面）。
// 要看它们：读部署配置 [`docs/spec/config.md`](../../docs/spec/config.md)。
//
// 同理**不**返回：白名单/隔离名单的**内容**、任何密钥（`ST-20`）、以及进程 `started_at`。
//
// 为什么不要 `started_at`：核心全库**零** `time.Now()`（`MD-6` 的纪律）——
// 不为了一个展示字段开这个口子。要看「核心是不是刚重启」，控制台「概览」的事件时间范围
// 已经能回答（重启后事件从零开始）。
type CoreSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ── 策略面（`AR-13` / `ST-8`）─────────────────────────────────────
	PolicyId       string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion  uint64 `protobuf:"varint,2,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyChecksum string `protobuf:"bytes,3,opt,name=policy_checksum,json=policyChecksum,proto3" json:"policy_checksum,omitempty"`
	// rule_count 是判定规则条数（规则 id 已随事件载荷的 `signals` 可见，条数严格更弱）。
	RuleCount int32 `protobuf:"varint,4,opt,name=rule_count,json=ruleCount,proto3" json:"rule_count,omitempty"`
	// whitelist_count 只给**条数**（名单内容是接入方的资产面，不进观测面）。
	WhitelistCount int32 `protobuf:"varint,5,opt,name=whitelist_count,json=whitelistCount,proto3" json:"whitelist_count,omitempty"`
	// ── AI 能力（`ADR-0023` / `ADR-0026`）────────────────────────────
	AiEnabled         bool     `protobuf:"varint,6,opt,name=ai_enabled,json=aiEnabled,proto3" json:"ai_enabled,omitempty"`
	AiKinds           []string `protobuf:"bytes,7,rep,name=ai_kinds,json=aiKinds,proto3" json:"ai_kinds,omitempty"`
	AiModel           string   `protobuf:"bytes,8,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	AiManifestPath    string   `protobuf:"bytes,9,opt,name=ai_manifest_path,json=aiManifestPath,proto3" json:"ai_manifest_path,omitempty"`
	AiContentVariants int32    `protobuf:"varint,10,opt,name=ai_content_variants,json=aiContentVariants,proto3" json:"ai_content_variants,omitempty"`
	AiRotateCooldown  string   `protobuf:"bytes,11,opt,name=ai_rotate_cooldown,json=aiRotateCooldown,proto3" json:"ai_rotate_cooldown,omitempty"`
	// ai_manifest_loaded = 是否真的装载成功（false 且 enabled=true ⇒ 「开关开了但没内容」）。
	AiManifestLoaded    bool   `protobuf:"varint,12,opt,name=ai_manifest_loaded,json=aiManifestLoaded,proto3" json:"ai_manifest_loaded,omitempty"`
	AiManifestVersion   uint64 `protobuf:"varint,13,opt,name=ai_manifest_version,json=aiManifestVersion,proto3" json:"ai_manifest_version,omitempty"`
	AiManifestResources int32  `protobuf:"varint,14,opt,name=ai_manifest_resources,json=aiManifestResources,proto3" json:"ai_manifest_resources,omitempty"`
	AiManifestContents  int32  `protobuf:"varint,15,opt,name=ai_manifest_contents,json=aiManifestContents,proto3" json:"ai_manifest_contents,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CoreSnapshot) Reset() {
	*x = CoreSnapshot{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreSnapshot) ProtoMessage() {}

func (x *CoreSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreSnapshot.ProtoReflect.Descriptor instead.
func (*CoreSnapshot) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *CoreSnapshot) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *CoreSnapshot) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *CoreSnapshot) GetPolicyChecksum() string {
	if x != nil {
		return x.PolicyChecksum
	}
	return ""
}

func (x *CoreSnapshot) GetRuleCount() int32 {
	if x != nil {
		return x.RuleCount
	}
	return 0
}

func (x *CoreSnapshot) GetWhitelistCount() int32 {
	if x != nil {
		return x.WhitelistCount
	}
	return 0
}

func (x *CoreSnapshot) GetAiEnabled() bool {
	if x != nil {
		return x.AiEnabled
	}
	return false
}

func (x *CoreSnapshot) GetAiKinds() []string {
	if x != nil {
		return x.AiKinds
	}
	return nil
}

func (x *CoreSnapshot) GetAiModel() string {
	if x != nil {
		return x.AiModel
	}
	return ""
}

func (x *CoreSnapshot) GetAiManifestPath() string {
	if x != nil {
		return x.AiManifestPath
	}
	return ""
}

func (x *CoreSnapshot) GetAiContentVariants() int32 {
	if x != nil {
		return x.AiContentVariants
	}
	return 0
}

func (x *CoreSnapshot) GetAiRotateCooldown() string {
	if x != nil {
		return x.AiRotateCooldown
	}
	return ""
}

func (x *CoreSnapshot) GetAiManifestLoaded() bool {
	if x != nil {
		return x.AiManifestLoaded
	}
	return false
}

func (x *CoreSnapshot) GetAiManifestVersion() uint64 {
	if x != nil {
		return x.AiManifestVersion
	}
	return 0
}

func (x *CoreSnapshot) GetAiManifestResources() int32 {
	if x != nil {
		return x.AiManifestResources
	}
	return 0
}

func (x *CoreSnapshot) GetAiManifestContents() int32 {
	if x != nil {
		return x.AiManifestContents
	}
	return 0
}

type TelemetryEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 幂等键：重复上报不产生重复记录（AR-11 / ST-9）
	EventId   string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ActorId   string `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Payload   []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// 由调用方注入（MD-6：核心禁止依赖系统时钟做判定）
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *TelemetryEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TelemetryEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TelemetryEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *TelemetryEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TelemetryEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TelemetryEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TelemetryBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TelemetryEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *TelemetryBatch) GetEvents() []*TelemetryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ListEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 返回条数上限；0 = 服务端默认（200）。
	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// 只返回该时刻之后的事件；不填 = 不限。
	Since *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	// 只看某类事件（如 request_judged）；空 = 不限。
	EventType     string `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *ListEventsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEventsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListEventsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TelemetryEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *ListEventsResponse) GetEvents() []*TelemetryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint32                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Duplicated    uint32                 `protobuf:"varint,2,opt,name=duplicated,proto3" json:"duplicated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *ReportAck) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *ReportAck) GetDuplicated() uint32 {
	if x != nil {
		return x.Duplicated
	}
	return 0
}

var File_telemetry_v1_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1ctelemetry/v1/telemetry.proto\x12\ftelemetry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x01\n" +
	"\x12WatchEventsRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12$\n" +
	"\x0ecatch_up_limit\x18\x03 \x01(\rR\fcatchUpLimit\x12#\n" +
	"\rsubscriber_id\x18\x04 \x01(\tR\fsubscriberId\"\x7f\n" +
	"\n" +
	"WatchEvent\x124\n" +
	"\x05event\x18\x01 \x01(\v2\x1c.telemetry.v1.TelemetryEventH\x00R\x05event\x123\n" +
	"\x06status\x18\x02 \x01(\v2\x19.telemetry.v1.WatchStatusH\x00R\x06statusB\x06\n" +
	"\x04body\"d\n" +
	"\vWatchStatus\x12\x18\n" +
	"\adropped\x18\x01 \x01(\x04R\adropped\x12\x1f\n" +
	"\vbuffer_size\x18\x02 \x01(\rR\n" +
	"bufferSize\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\rR\bcapacity\"\x18\n" +
	"\x16GetCoreSnapshotRequest\"\xe4\x04\n" +
	"\fCoreSnapshot\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\x02 \x01(\x04R\rpolicyVersion\x12'\n" +
	"\x0fpolicy_checksum\x18\x03 \x01(\tR\x0epolicyChecksum\x12\x1d\n" +
	"\n" +
	"rule_count\x18\x04 \x01(\x05R\truleCount\x12'\n" +
	"\x0fwhitelist_count\x18\x05 \x01(\x05R\x0ewhitelistCount\x12\x1d\n" +
	"\n" +
	"ai_enabled\x18\x06 \x01(\bR\taiEnabled\x12\x19\n" +
	"\bai_kinds\x18\a \x03(\tR\aaiKinds\x12\x19\n" +
	"\bai_model\x18\b \x01(\tR\aaiModel\x12(\n" +
	"\x10ai_manifest_path\x18\t \x01(\tR\x0eaiManifestPath\x12.\n" +
	"\x13ai_content_variants\x18\n" +
	" \x01(\x05R\x11aiContentVariants\x12,\n" +
	"\x12ai_rotate_cooldown\x18\v \x01(\tR\x10aiRotateCooldown\x12,\n" +
	"\x12ai_manifest_loaded\x18\f \x01(\bR\x10aiManifestLoaded\x12.\n" +
	"\x13ai_manifest_version\x18\r \x01(\x04R\x11aiManifestVersion\x122\n" +
	"\x15ai_manifest_resources\x18\x0e \x01(\x05R\x13aiManifestResources\x120\n" +
	"\x14ai_manifest_contents\x18\x0f \x01(\x05R\x12aiManifestContents\"\xd9\x01\n" +
	"\x0eTelemetryEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"F\n" +
	"\x0eTelemetryBatch\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.telemetry.v1.TelemetryEventR\x06events\"z\n" +
	"\x11ListEventsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\"J\n" +
	"\x12ListEventsResponse\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.telemetry.v1.TelemetryEventR\x06events\"G\n" +
	"\tReportAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\rR\baccepted\x12\x1e\n" +
	"\n" +
	"duplicated\x18\x02 \x01(\rR\n" +
	"duplicated2\x8e\x03\n" +
	"\x12DeceptionTelemetry\x12?\n" +
	"\x06Report\x12\x1c.telemetry.v1.TelemetryEvent\x1a\x17.telemetry.v1.ReportAck\x12D\n" +
	"\vReportBatch\x12\x1c.telemetry.v1.TelemetryBatch\x1a\x17.telemetry.v1.ReportAck\x12O\n" +
	"\n" +
	"ListEvents\x12\x1f.telemetry.v1.ListEventsRequest\x1a .telemetry.v1.ListEventsResponse\x12S\n" +
	"\x0fGetCoreSnapshot\x12$.telemetry.v1.GetCoreSnapshotRequest\x1a\x1a.telemetry.v1.CoreSnapshot\x12K\n" +
	"\vWatchEvents\x12 .telemetry.v1.WatchEventsRequest\x1a\x18.telemetry.v1.WatchEvent0\x01B#Z!shen/api/telemetry/v1;telemetryv1b\x06proto3"

var (
	file_telemetry_v1_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_v1_telemetry_proto_rawDescData []byte
)

func file_telemetry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)))
	})
	return file_telemetry_v1_telemetry_proto_rawDescData
}

var file_telemetry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_telemetry_v1_telemetry_proto_goTypes = []any{
	(*WatchEventsRequest)(nil),     // 0: telemetry.v1.WatchEventsRequest
	(*WatchEvent)(nil),             // 1: telemetry.v1.WatchEvent
	(*WatchStatus)(nil),            // 2: telemetry.v1.WatchStatus
	(*GetCoreSnapshotRequest)(nil), // 3: telemetry.v1.GetCoreSnapshotRequest
	(*CoreSnapshot)(nil),           // 4: telemetry.v1.CoreSnapshot
	(*TelemetryEvent)(nil),         // 5: telemetry.v1.TelemetryEvent
	(*TelemetryBatch)(nil),         // 6: telemetry.v1.TelemetryBatch
	(*ListEventsRequest)(nil),      // 7: telemetry.v1.ListEventsRequest
	(*ListEventsResponse)(nil),     // 8: telemetry.v1.ListEventsResponse
	(*ReportAck)(nil),              // 9: telemetry.v1.ReportAck
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
}
var file_telemetry_v1_telemetry_proto_depIdxs = []int32{
	10, // 0: telemetry.v1.WatchEventsRequest.since:type_name -> google.protobuf.Timestamp
	5,  // 1: telemetry.v1.WatchEvent.event:type_name -> telemetry.v1.TelemetryEvent
	2,  // 2: telemetry.v1.WatchEvent.status:type_name -> telemetry.v1.WatchStatus
	10, // 3: telemetry.v1.TelemetryEvent.created_at:type_name -> google.protobuf.Timestamp
	5,  // 4: telemetry.v1.TelemetryBatch.events:type_name -> telemetry.v1.TelemetryEvent
	10, // 5: telemetry.v1.ListEventsRequest.since:type_name -> google.protobuf.Timestamp
	5,  // 6: telemetry.v1.ListEventsResponse.events:type_name -> telemetry.v1.TelemetryEvent
	5,  // 7: telemetry.v1.DeceptionTelemetry.Report:input_type -> telemetry.v1.TelemetryEvent
	6,  // 8: telemetry.v1.DeceptionTelemetry.ReportBatch:input_type -> telemetry.v1.TelemetryBatch
	7,  // 9: telemetry.v1.DeceptionTelemetry.ListEvents:input_type -> telemetry.v1.ListEventsRequest
	3,  // 10: telemetry.v1.DeceptionTelemetry.GetCoreSnapshot:input_type -> telemetry.v1.GetCoreSnapshotRequest
	0,  // 11: telemetry.v1.DeceptionTelemetry.WatchEvents:input_type -> telemetry.v1.WatchEventsRequest
	9,  // 12: telemetry.v1.DeceptionTelemetry.Report:output_type -> telemetry.v1.ReportAck
	9,  // 13: telemetry.v1.DeceptionTelemetry.ReportBatch:output_type -> telemetry.v1.ReportAck
	8,  // 14: telemetry.v1.DeceptionTelemetry.ListEvents:output_type -> telemetry.v1.ListEventsResponse
	4,  // 15: telemetry.v1.DeceptionTelemetry.GetCoreSnapshot:output_type -> telemetry.v1.CoreSnapshot
	1,  // 16: telemetry.v1.DeceptionTelemetry.WatchEvents:output_type -> telemetry.v1.WatchEvent
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_telemetry_v1_telemetry_proto_init() }
func file_telemetry_v1_telemetry_proto_init() {
	if File_telemetry_v1_telemetry_proto != nil {
		return
	}
	file_telemetry_v1_telemetry_proto_msgTypes[1].OneofWrappers = []any{
		(*WatchEvent_Event)(nil),
		(*WatchEvent_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_v1_telemetry_proto = out.File
	file_telemetry_v1_telemetry_proto_goTypes = nil
	file_telemetry_v1_telemetry_proto_depIdxs = nil
}
