// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: telemetry/v1/telemetry.proto

package telemetryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeceptionTelemetry_Report_FullMethodName          = "/telemetry.v1.DeceptionTelemetry/Report"
	DeceptionTelemetry_ReportBatch_FullMethodName     = "/telemetry.v1.DeceptionTelemetry/ReportBatch"
	DeceptionTelemetry_ListEvents_FullMethodName      = "/telemetry.v1.DeceptionTelemetry/ListEvents"
	DeceptionTelemetry_GetCoreSnapshot_FullMethodName = "/telemetry.v1.DeceptionTelemetry/GetCoreSnapshot"
)

// DeceptionTelemetryClient is the client API for DeceptionTelemetry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 遥测面 —— 异步、批量、幂等（AR-11）
type DeceptionTelemetryClient interface {
	Report(ctx context.Context, in *TelemetryEvent, opts ...grpc.CallOption) (*ReportAck, error)
	ReportBatch(ctx context.Context, in *TelemetryBatch, opts ...grpc.CallOption) (*ReportAck, error)
	// 读侧：列出最近事件（观测面）。
	//
	// 用途：控制台回答「刚才发生了什么、告警在哪、流量怎么流动」——
	// 这是**人工测试与排障**的基础能力，也是 `logs.md` 字典落地前的过渡读侧契约。
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	// 读侧：**核心当前生效状态的只读快照**（配置 + 策略版本 + AI 能力装载态）。
	//
	// 用途：控制台回答「这套引擎现在是按什么在跑」—— 配置与内容清单活在**核心内存**里，
	// 控制台拿不到，只能问核心要（见 `docs/spec/console-api.md` §2）。
	//
	// 语义：**纯读**。与 `policy.Pull` 不同：它**不**推进任何游标、**不**写任何状态 ——
	// 控制台随时刷新都不会影响适配器的策略对账（`ST-8`）。
	//
	// 刻意**不**返回：白名单/隔离名单的**内容**（只给条数）、任何密钥（`ST-20`）。
	// 观测面不等于泄密面：控制台是只读观测台，不是配置导出器。
	GetCoreSnapshot(ctx context.Context, in *GetCoreSnapshotRequest, opts ...grpc.CallOption) (*CoreSnapshot, error)
}

type deceptionTelemetryClient struct {
	cc grpc.ClientConnInterface
}

func NewDeceptionTelemetryClient(cc grpc.ClientConnInterface) DeceptionTelemetryClient {
	return &deceptionTelemetryClient{cc}
}

func (c *deceptionTelemetryClient) Report(ctx context.Context, in *TelemetryEvent, opts ...grpc.CallOption) (*ReportAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportAck)
	err := c.cc.Invoke(ctx, DeceptionTelemetry_Report_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deceptionTelemetryClient) ReportBatch(ctx context.Context, in *TelemetryBatch, opts ...grpc.CallOption) (*ReportAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportAck)
	err := c.cc.Invoke(ctx, DeceptionTelemetry_ReportBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deceptionTelemetryClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, DeceptionTelemetry_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deceptionTelemetryClient) GetCoreSnapshot(ctx context.Context, in *GetCoreSnapshotRequest, opts ...grpc.CallOption) (*CoreSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoreSnapshot)
	err := c.cc.Invoke(ctx, DeceptionTelemetry_GetCoreSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeceptionTelemetryServer is the server API for DeceptionTelemetry service.
// All implementations must embed UnimplementedDeceptionTelemetryServer
// for forward compatibility.
//
// 遥测面 —— 异步、批量、幂等（AR-11）
type DeceptionTelemetryServer interface {
	Report(context.Context, *TelemetryEvent) (*ReportAck, error)
	ReportBatch(context.Context, *TelemetryBatch) (*ReportAck, error)
	// 读侧：列出最近事件（观测面）。
	//
	// 用途：控制台回答「刚才发生了什么、告警在哪、流量怎么流动」——
	// 这是**人工测试与排障**的基础能力，也是 `logs.md` 字典落地前的过渡读侧契约。
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	// 读侧：**核心当前生效状态的只读快照**（配置 + 策略版本 + AI 能力装载态）。
	//
	// 用途：控制台回答「这套引擎现在是按什么在跑」—— 配置与内容清单活在**核心内存**里，
	// 控制台拿不到，只能问核心要（见 `docs/spec/console-api.md` §2）。
	//
	// 语义：**纯读**。与 `policy.Pull` 不同：它**不**推进任何游标、**不**写任何状态 ——
	// 控制台随时刷新都不会影响适配器的策略对账（`ST-8`）。
	//
	// 刻意**不**返回：白名单/隔离名单的**内容**（只给条数）、任何密钥（`ST-20`）。
	// 观测面不等于泄密面：控制台是只读观测台，不是配置导出器。
	GetCoreSnapshot(context.Context, *GetCoreSnapshotRequest) (*CoreSnapshot, error)
	mustEmbedUnimplementedDeceptionTelemetryServer()
}

// UnimplementedDeceptionTelemetryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeceptionTelemetryServer struct{}

func (UnimplementedDeceptionTelemetryServer) Report(context.Context, *TelemetryEvent) (*ReportAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedDeceptionTelemetryServer) ReportBatch(context.Context, *TelemetryBatch) (*ReportAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportBatch not implemented")
}
func (UnimplementedDeceptionTelemetryServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedDeceptionTelemetryServer) GetCoreSnapshot(context.Context, *GetCoreSnapshotRequest) (*CoreSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoreSnapshot not implemented")
}
func (UnimplementedDeceptionTelemetryServer) mustEmbedUnimplementedDeceptionTelemetryServer() {}
func (UnimplementedDeceptionTelemetryServer) testEmbeddedByValue()                            {}

// UnsafeDeceptionTelemetryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeceptionTelemetryServer will
// result in compilation errors.
type UnsafeDeceptionTelemetryServer interface {
	mustEmbedUnimplementedDeceptionTelemetryServer()
}

func RegisterDeceptionTelemetryServer(s grpc.ServiceRegistrar, srv DeceptionTelemetryServer) {
	// If the following call panics, it indicates UnimplementedDeceptionTelemetryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeceptionTelemetry_ServiceDesc, srv)
}

func _DeceptionTelemetry_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeceptionTelemetryServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeceptionTelemetry_Report_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeceptionTelemetryServer).Report(ctx, req.(*TelemetryEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeceptionTelemetry_ReportBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeceptionTelemetryServer).ReportBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeceptionTelemetry_ReportBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeceptionTelemetryServer).ReportBatch(ctx, req.(*TelemetryBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeceptionTelemetry_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeceptionTelemetryServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeceptionTelemetry_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeceptionTelemetryServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeceptionTelemetry_GetCoreSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoreSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeceptionTelemetryServer).GetCoreSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeceptionTelemetry_GetCoreSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeceptionTelemetryServer).GetCoreSnapshot(ctx, req.(*GetCoreSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeceptionTelemetry_ServiceDesc is the grpc.ServiceDesc for DeceptionTelemetry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeceptionTelemetry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.v1.DeceptionTelemetry",
	HandlerType: (*DeceptionTelemetryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _DeceptionTelemetry_Report_Handler,
		},
		{
			MethodName: "ReportBatch",
			Handler:    _DeceptionTelemetry_ReportBatch_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _DeceptionTelemetry_ListEvents_Handler,
		},
		{
			MethodName: "GetCoreSnapshot",
			Handler:    _DeceptionTelemetry_GetCoreSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "telemetry/v1/telemetry.proto",
}
