// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: policy/v1/policy.proto

package policyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyPullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyPullRequest) Reset() {
	*x = PolicyPullRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyPullRequest) ProtoMessage() {}

func (x *PolicyPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyPullRequest.ProtoReflect.Descriptor instead.
func (*PolicyPullRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyPullRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type PolicySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                // 单调递增；回滚即发布新版本
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                 // 适配器可直接消费的策略体（文档：docs/spec/policy-payload.md）
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`               // 对上方 payload **字节**的 SHA-256（十六进制）：适配器先验完整性再应用
	GrayPct       uint32                 `protobuf:"varint,5,opt,name=gray_pct,json=grayPct,proto3" json:"gray_pct,omitempty"` // 灰度比例
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySnapshot) Reset() {
	*x = PolicySnapshot{}
	mi := &file_policy_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySnapshot) ProtoMessage() {}

func (x *PolicySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySnapshot.ProtoReflect.Descriptor instead.
func (*PolicySnapshot) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *PolicySnapshot) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicySnapshot) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicySnapshot) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PolicySnapshot) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *PolicySnapshot) GetGrayPct() uint32 {
	if x != nil {
		return x.GrayPct
	}
	return 0
}

type PolicyWatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	KnownVersion  uint64                 `protobuf:"varint,2,opt,name=known_version,json=knownVersion,proto3" json:"known_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyWatchRequest) Reset() {
	*x = PolicyWatchRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyWatchRequest) ProtoMessage() {}

func (x *PolicyWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyWatchRequest.ProtoReflect.Descriptor instead.
func (*PolicyWatchRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyWatchRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyWatchRequest) GetKnownVersion() uint64 {
	if x != nil {
		return x.KnownVersion
	}
	return 0
}

type PolicyDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *PolicySnapshot        `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyDelta) Reset() {
	*x = PolicyDelta{}
	mi := &file_policy_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDelta) ProtoMessage() {}

func (x *PolicyDelta) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDelta.ProtoReflect.Descriptor instead.
func (*PolicyDelta) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyDelta) GetSnapshot() *PolicySnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// 回执，用于版本对账（AR-13）
type PolicyAck struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PolicyId string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Version  uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Applied  bool                   `protobuf:"varint,3,opt,name=applied,proto3" json:"applied,omitempty"`
	// 上报回执的适配器标识（例：proxy@10.0.0.5:8081）。
	// 没有它就只知道「有人应用了」，不知道「谁应用了」—— 版本对账会变成一笔糊涂账。
	AdapterId string `protobuf:"bytes,4,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	// applied=false 时的原因（校验和不匹配 / 载荷非法 / 后端建不出来）。
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyAck) Reset() {
	*x = PolicyAck{}
	mi := &file_policy_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyAck) ProtoMessage() {}

func (x *PolicyAck) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyAck.ProtoReflect.Descriptor instead.
func (*PolicyAck) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *PolicyAck) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyAck) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyAck) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *PolicyAck) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *PolicyAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PolicyAckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyAckReply) Reset() {
	*x = PolicyAckReply{}
	mi := &file_policy_v1_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyAckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyAckReply) ProtoMessage() {}

func (x *PolicyAckReply) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyAckReply.ProtoReflect.Descriptor instead.
func (*PolicyAckReply) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *PolicyAckReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_policy_v1_policy_proto protoreflect.FileDescriptor

const file_policy_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x16policy/v1/policy.proto\x12\tpolicy.v1\"0\n" +
	"\x11PolicyPullRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\"\x98\x01\n" +
	"\x0ePolicySnapshot\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\x12\x19\n" +
	"\bgray_pct\x18\x05 \x01(\rR\agrayPct\"V\n" +
	"\x12PolicyWatchRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12#\n" +
	"\rknown_version\x18\x02 \x01(\x04R\fknownVersion\"D\n" +
	"\vPolicyDelta\x125\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x19.policy.v1.PolicySnapshotR\bsnapshot\"\x93\x01\n" +
	"\tPolicyAck\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x18\n" +
	"\aapplied\x18\x03 \x01(\bR\aapplied\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x04 \x01(\tR\tadapterId\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\" \n" +
	"\x0ePolicyAckReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xcc\x01\n" +
	"\x0fDeceptionPolicy\x12?\n" +
	"\x04Pull\x12\x1c.policy.v1.PolicyPullRequest\x1a\x19.policy.v1.PolicySnapshot\x12@\n" +
	"\x05Watch\x12\x1d.policy.v1.PolicyWatchRequest\x1a\x16.policy.v1.PolicyDelta0\x01\x126\n" +
	"\x03Ack\x12\x14.policy.v1.PolicyAck\x1a\x19.policy.v1.PolicyAckReplyB\x1dZ\x1bshen/api/policy/v1;policyv1b\x06proto3"

var (
	file_policy_v1_policy_proto_rawDescOnce sync.Once
	file_policy_v1_policy_proto_rawDescData []byte
)

func file_policy_v1_policy_proto_rawDescGZIP() []byte {
	file_policy_v1_policy_proto_rawDescOnce.Do(func() {
		file_policy_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_v1_policy_proto_rawDesc), len(file_policy_v1_policy_proto_rawDesc)))
	})
	return file_policy_v1_policy_proto_rawDescData
}

var file_policy_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_policy_v1_policy_proto_goTypes = []any{
	(*PolicyPullRequest)(nil),  // 0: policy.v1.PolicyPullRequest
	(*PolicySnapshot)(nil),     // 1: policy.v1.PolicySnapshot
	(*PolicyWatchRequest)(nil), // 2: policy.v1.PolicyWatchRequest
	(*PolicyDelta)(nil),        // 3: policy.v1.PolicyDelta
	(*PolicyAck)(nil),          // 4: policy.v1.PolicyAck
	(*PolicyAckReply)(nil),     // 5: policy.v1.PolicyAckReply
}
var file_policy_v1_policy_proto_depIdxs = []int32{
	1, // 0: policy.v1.PolicyDelta.snapshot:type_name -> policy.v1.PolicySnapshot
	0, // 1: policy.v1.DeceptionPolicy.Pull:input_type -> policy.v1.PolicyPullRequest
	2, // 2: policy.v1.DeceptionPolicy.Watch:input_type -> policy.v1.PolicyWatchRequest
	4, // 3: policy.v1.DeceptionPolicy.Ack:input_type -> policy.v1.PolicyAck
	1, // 4: policy.v1.DeceptionPolicy.Pull:output_type -> policy.v1.PolicySnapshot
	3, // 5: policy.v1.DeceptionPolicy.Watch:output_type -> policy.v1.PolicyDelta
	5, // 6: policy.v1.DeceptionPolicy.Ack:output_type -> policy.v1.PolicyAckReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_policy_v1_policy_proto_init() }
func file_policy_v1_policy_proto_init() {
	if File_policy_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_v1_policy_proto_rawDesc), len(file_policy_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policy_v1_policy_proto_goTypes,
		DependencyIndexes: file_policy_v1_policy_proto_depIdxs,
		MessageInfos:      file_policy_v1_policy_proto_msgTypes,
	}.Build()
	File_policy_v1_policy_proto = out.File
	file_policy_v1_policy_proto_goTypes = nil
	file_policy_v1_policy_proto_depIdxs = nil
}
