// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: policy/v1/policy.proto

package policyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeceptionPolicy_Pull_FullMethodName  = "/policy.v1.DeceptionPolicy/Pull"
	DeceptionPolicy_Watch_FullMethodName = "/policy.v1.DeceptionPolicy/Watch"
	DeceptionPolicy_Ack_FullMethodName   = "/policy.v1.DeceptionPolicy/Ack"
)

// DeceptionPolicyClient is the client API for DeceptionPolicy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 策略面 —— 版本化、可灰度、可回滚、带回执（AR-13 / ST-8）
type DeceptionPolicyClient interface {
	Pull(ctx context.Context, in *PolicyPullRequest, opts ...grpc.CallOption) (*PolicySnapshot, error)
	Watch(ctx context.Context, in *PolicyWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PolicyDelta], error)
	Ack(ctx context.Context, in *PolicyAck, opts ...grpc.CallOption) (*PolicyAckReply, error)
}

type deceptionPolicyClient struct {
	cc grpc.ClientConnInterface
}

func NewDeceptionPolicyClient(cc grpc.ClientConnInterface) DeceptionPolicyClient {
	return &deceptionPolicyClient{cc}
}

func (c *deceptionPolicyClient) Pull(ctx context.Context, in *PolicyPullRequest, opts ...grpc.CallOption) (*PolicySnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicySnapshot)
	err := c.cc.Invoke(ctx, DeceptionPolicy_Pull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deceptionPolicyClient) Watch(ctx context.Context, in *PolicyWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PolicyDelta], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeceptionPolicy_ServiceDesc.Streams[0], DeceptionPolicy_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PolicyWatchRequest, PolicyDelta]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeceptionPolicy_WatchClient = grpc.ServerStreamingClient[PolicyDelta]

func (c *deceptionPolicyClient) Ack(ctx context.Context, in *PolicyAck, opts ...grpc.CallOption) (*PolicyAckReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyAckReply)
	err := c.cc.Invoke(ctx, DeceptionPolicy_Ack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeceptionPolicyServer is the server API for DeceptionPolicy service.
// All implementations must embed UnimplementedDeceptionPolicyServer
// for forward compatibility.
//
// 策略面 —— 版本化、可灰度、可回滚、带回执（AR-13 / ST-8）
type DeceptionPolicyServer interface {
	Pull(context.Context, *PolicyPullRequest) (*PolicySnapshot, error)
	Watch(*PolicyWatchRequest, grpc.ServerStreamingServer[PolicyDelta]) error
	Ack(context.Context, *PolicyAck) (*PolicyAckReply, error)
	mustEmbedUnimplementedDeceptionPolicyServer()
}

// UnimplementedDeceptionPolicyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeceptionPolicyServer struct{}

func (UnimplementedDeceptionPolicyServer) Pull(context.Context, *PolicyPullRequest) (*PolicySnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedDeceptionPolicyServer) Watch(*PolicyWatchRequest, grpc.ServerStreamingServer[PolicyDelta]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedDeceptionPolicyServer) Ack(context.Context, *PolicyAck) (*PolicyAckReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedDeceptionPolicyServer) mustEmbedUnimplementedDeceptionPolicyServer() {}
func (UnimplementedDeceptionPolicyServer) testEmbeddedByValue()                         {}

// UnsafeDeceptionPolicyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeceptionPolicyServer will
// result in compilation errors.
type UnsafeDeceptionPolicyServer interface {
	mustEmbedUnimplementedDeceptionPolicyServer()
}

func RegisterDeceptionPolicyServer(s grpc.ServiceRegistrar, srv DeceptionPolicyServer) {
	// If the following call panics, it indicates UnimplementedDeceptionPolicyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeceptionPolicy_ServiceDesc, srv)
}

func _DeceptionPolicy_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyPullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeceptionPolicyServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeceptionPolicy_Pull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeceptionPolicyServer).Pull(ctx, req.(*PolicyPullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeceptionPolicy_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PolicyWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeceptionPolicyServer).Watch(m, &grpc.GenericServerStream[PolicyWatchRequest, PolicyDelta]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeceptionPolicy_WatchServer = grpc.ServerStreamingServer[PolicyDelta]

func _DeceptionPolicy_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyAck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeceptionPolicyServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeceptionPolicy_Ack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeceptionPolicyServer).Ack(ctx, req.(*PolicyAck))
	}
	return interceptor(ctx, in, info, handler)
}

// DeceptionPolicy_ServiceDesc is the grpc.ServiceDesc for DeceptionPolicy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeceptionPolicy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "policy.v1.DeceptionPolicy",
	HandlerType: (*DeceptionPolicyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pull",
			Handler:    _DeceptionPolicy_Pull_Handler,
		},
		{
			MethodName: "Ack",
			Handler:    _DeceptionPolicy_Ack_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _DeceptionPolicy_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "policy/v1/policy.proto",
}
